version: '3.4'

services:
  animalexibition_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "5432:5432"
    networks:
      - shared_animalexhibition
    volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  animalexibition_redis:
    ports:
      - '6379:6379'
    networks:
      - shared_animalexhibition
    volumes:      
      - ~/.docker-conf/redis/data/:/data

  animalexhibition.api:
    ports:
      - "10000:80"
    networks:
      - shared_animalexhibition
    env_file:
      - env.api  
networks:
  shared_animalexhibition:
    name: animal_exhibition
    driver: bridge